/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sysIag.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.maintabpanel',

    requires: [
        'sysIag.view.PhonesTabPanel',
        'Ext.tab.Bar',
        'Ext.Img',
        'Ext.tab.Panel'
    ],

    config: {
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'container',
                title: 'Начало',
                iconCls: 'home',
                layout: 'fit',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        title: 'https://system.iag.bg'
                    },
                    {
                        xtype: 'image',
                        centered: true,
                        height: 518,
                        width: 318,
                        src: 'resources/images/Home.png'
                    }
                ]
            },
            {
                xtype: 'phonestabpanel',
                title: 'Телефони',
                iconCls: 'team'
            }
        ]
    }

});