function _4a464afbf2859ea3d6d9f4d742f1de5b5e7b8872(){};/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'userPhone',
        'PodeleniaModel',
        'LoginModel'
    ],
    stores: [
        'iagPhone',
        'RdgtaStore',
        'RdgtaUsers',
        'DgsStore',
        'searchByName',
        'searchByNumber',
        'LoginStore'
    ],
    views: [
        'MainTabPanel',
        'iagPhoneList',
        'PhonesTabPanel',
        'RdgNav',
        'RdgtaList',
        'RdgtaUsersList',
        'RdgDgsNav',
        'RdgtaDgsList',
        'DgsList',
        'DgsUsersList',
        'SearchByNameList',
        'SearchTabPanel',
        'SearchByNumberList',
        'LoginPanel'
    ],
    controllers: [
        'Iag',
        'RdgAndDgs',
        'Func',
        'Search',
        'Login'
    ],
    name: 'sysIag',

    launch: function() {

        Ext.create('sysIag.view.LoginPanel', {fullscreen: true});
    }

});
