/*
 * File: app/controller/Search.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sysIag.controller.Search', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            searchbyname: '#searchbyname',
            searchbynumber: '#searchbynumber',
            searchbynamelist: 'searchbynamelist',
            searchbynumberlist: 'searchbynumberlist'
        },

        control: {
            "searchbyname": {
                keyup: 'onSearchByNameKeyup',
                clearicontap: 'onSearchByNameClearicontap'
            },
            "searchbynamelist": {
                itemtap: 'onSearchByNameListItemTap',
                show: 'onSearchByNameListShow',
                activate: 'onSearchByNameListActivate'
            },
            "searchbynumberlist": {
                show: 'onSearchByNumberListShow',
                activate: 'onSearchByNumberListActivate1',
                itemtap: 'onSearchByNumberListItemTap'
            },
            "searchbynumber": {
                keyup: 'onSearchByNumberKeyup',
                paste: 'onSearchByNumberPaste'
            }
        }
    },

    onSearchByNameKeyup: function(textfield, e, eOpts) {

        this.getApplication().getController('Func').searchByName('searchByName', textfield);

    },

    onSearchByNameListItemTap: function(dataview, index, target, record, e, eOpts) {

        this.getApplication().getController('Func').callAndEmailFn(record);

    },

    onSearchByNameListShow: function(component, eOpts) {

        console.log('show serchbynamelist');

    },

    onSearchByNumberListShow: function(component, eOpts) {
        console.log('show serchbynumberlist');
    },

    onSearchByNameListActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        console.log('SearchByNameListActivate');
    },

    onSearchByNumberListActivate1: function(newActiveItem, container, oldActiveItem, eOpts) {
        console.log('SearchByNumberListActivate');
    },

    onSearchByNameClearicontap: function(textfield, e, eOpts) {

        console.log('clearicontap');

    },

    onSearchByNumberKeyup: function(textfield, e, eOpts) {

        this.getApplication().getController('Func').searchByNumber('searchByNumber', textfield);

    },

    onSearchByNumberPaste: function(textfield, e, eOpts) {

        this.getApplication().getController('Func').searchByNumber('searchByNumber', textfield);

    },

    onSearchByNumberListItemTap: function(dataview, index, target, record, e, eOpts) {

        this.getApplication().getController('Func').callAndEmailFn(record);

    }

});